from django.core.management.base import BaseCommand
COUNTRIES = [
    {"name": "Afghanistan", "code": "AF", "phone_code": "+93", "flag_emoji": "🇦🇫", "currency_code": "AFN", "currency_symbol": "؋"},
    {"name": "Albania", "code": "AL", "phone_code": "+355", "flag_emoji": "🇦🇱", "currency_code": "ALL", "currency_symbol": "L"},
    {"name": "Algeria", "code": "DZ", "phone_code": "+213", "flag_emoji": "🇩🇿", "currency_code": "DZD", "currency_symbol": "د.ج"},
    {"name": "Argentina", "code": "AR", "phone_code": "+54", "flag_emoji": "🇦🇷", "currency_code": "ARS", "currency_symbol": "$"},
    {"name": "Armenia", "code": "AM", "phone_code": "+374", "flag_emoji": "🇦🇲", "currency_code": "AMD", "currency_symbol": "֏"},
    {"name": "Australia", "code": "AU", "phone_code": "+61", "flag_emoji": "🇦🇺", "currency_code": "AUD", "currency_symbol": "$"},
    {"name": "Austria", "code": "AT", "phone_code": "+43", "flag_emoji": "🇦🇹", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Azerbaijan", "code": "AZ", "phone_code": "+994", "flag_emoji": "🇦🇿", "currency_code": "AZN", "currency_symbol": "₼"},
    {"name": "Bahrain", "code": "BH", "phone_code": "+973", "flag_emoji": "🇧🇭", "currency_code": "BHD", "currency_symbol": ".د.ب"},
    {"name": "Bangladesh", "code": "BD", "phone_code": "+880", "flag_emoji": "🇧🇩", "currency_code": "BDT", "currency_symbol": "৳"},
    {"name": "Belarus", "code": "BY", "phone_code": "+375", "flag_emoji": "🇧🇾", "currency_code": "BYN", "currency_symbol": "Br"},
    {"name": "Belgium", "code": "BE", "phone_code": "+32", "flag_emoji": "🇧🇪", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Benin", "code": "BJ", "phone_code": "+229", "flag_emoji": "🇧🇯", "currency_code": "XOF", "currency_symbol": "Fr"},
    {"name": "Bolivia", "code": "BO", "phone_code": "+591", "flag_emoji": "🇧🇴", "currency_code": "BOB", "currency_symbol": "Bs."},
    {"name": "Bosnia and Herzegovina", "code": "BA", "phone_code": "+387", "flag_emoji": "🇧🇦", "currency_code": "BAM", "currency_symbol": "KM"},
    {"name": "Botswana", "code": "BW", "phone_code": "+267", "flag_emoji": "🇧🇼", "currency_code": "BWP", "currency_symbol": "P"},
    {"name": "Brazil", "code": "BR", "phone_code": "+55", "flag_emoji": "🇧🇷", "currency_code": "BRL", "currency_symbol": "R$"},
    {"name": "Brunei", "code": "BN", "phone_code": "+673", "flag_emoji": "🇧🇳", "currency_code": "BND", "currency_symbol": "$"},
    {"name": "Bulgaria", "code": "BG", "phone_code": "+359", "flag_emoji": "🇧🇬", "currency_code": "BGN", "currency_symbol": "лв"},
    {"name": "Burkina Faso", "code": "BF", "phone_code": "+226", "flag_emoji": "🇧🇫", "currency_code": "XOF", "currency_symbol": "Fr"},
    {"name": "Burundi", "code": "BI", "phone_code": "+257", "flag_emoji": "🇧🇮", "currency_code": "BIF", "currency_symbol": "Fr"},
    {"name": "Cambodia", "code": "KH", "phone_code": "+855", "flag_emoji": "🇰🇭", "currency_code": "KHR", "currency_symbol": "៛"},
    {"name": "Cameroon", "code": "CM", "phone_code": "+237", "flag_emoji": "🇨🇲", "currency_code": "XAF", "currency_symbol": "Fr"},
    {"name": "Canada", "code": "CA", "phone_code": "+1", "flag_emoji": "🇨🇦", "currency_code": "CAD", "currency_symbol": "$"},
    {"name": "Chad", "code": "TD", "phone_code": "+235", "flag_emoji": "🇹🇩", "currency_code": "XAF", "currency_symbol": "Fr"},
    {"name": "Chile", "code": "CL", "phone_code": "+56", "flag_emoji": "🇨🇱", "currency_code": "CLP", "currency_symbol": "$"},
    {"name": "China", "code": "CN", "phone_code": "+86", "flag_emoji": "🇨🇳", "currency_code": "CNY", "currency_symbol": "¥"},
    {"name": "Colombia", "code": "CO", "phone_code": "+57", "flag_emoji": "🇨🇴", "currency_code": "COP", "currency_symbol": "$"},
    {"name": "Congo", "code": "CG", "phone_code": "+242", "flag_emoji": "🇨🇬", "currency_code": "XAF", "currency_symbol": "Fr"},
    {"name": "Costa Rica", "code": "CR", "phone_code": "+506", "flag_emoji": "🇨🇷", "currency_code": "CRC", "currency_symbol": "₡"},
    {"name": "Croatia", "code": "HR", "phone_code": "+385", "flag_emoji": "🇭🇷", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Cuba", "code": "CU", "phone_code": "+53", "flag_emoji": "🇨🇺", "currency_code": "CUP", "currency_symbol": "$"},
    {"name": "Cyprus", "code": "CY", "phone_code": "+357", "flag_emoji": "🇨🇾", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Czech Republic", "code": "CZ", "phone_code": "+420", "flag_emoji": "🇨🇿", "currency_code": "CZK", "currency_symbol": "Kč"},
    {"name": "Denmark", "code": "DK", "phone_code": "+45", "flag_emoji": "🇩🇰", "currency_code": "DKK", "currency_symbol": "kr"},
    {"name": "Dominican Republic", "code": "DO", "phone_code": "+1-809", "flag_emoji": "🇩🇴", "currency_code": "DOP", "currency_symbol": "$"},
    {"name": "DR Congo", "code": "CD", "phone_code": "+243", "flag_emoji": "🇨🇩", "currency_code": "CDF", "currency_symbol": "Fr"},
    {"name": "Ecuador", "code": "EC", "phone_code": "+593", "flag_emoji": "🇪🇨", "currency_code": "USD", "currency_symbol": "$"},
    {"name": "Egypt", "code": "EG", "phone_code": "+20", "flag_emoji": "🇪🇬", "currency_code": "EGP", "currency_symbol": "£"},
    {"name": "El Salvador", "code": "SV", "phone_code": "+503", "flag_emoji": "🇸🇻", "currency_code": "USD", "currency_symbol": "$"},
    {"name": "Eritrea", "code": "ER", "phone_code": "+291", "flag_emoji": "🇪🇷", "currency_code": "ERN", "currency_symbol": "Nfk"},
    {"name": "Estonia", "code": "EE", "phone_code": "+372", "flag_emoji": "🇪🇪", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Eswatini", "code": "SZ", "phone_code": "+268", "flag_emoji": "🇸🇿", "currency_code": "SZL", "currency_symbol": "L"},
    {"name": "Ethiopia", "code": "ET", "phone_code": "+251", "flag_emoji": "🇪🇹", "currency_code": "ETB", "currency_symbol": "Br"},
    {"name": "Finland", "code": "FI", "phone_code": "+358", "flag_emoji": "🇫🇮", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "France", "code": "FR", "phone_code": "+33", "flag_emoji": "🇫🇷", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Gabon", "code": "GA", "phone_code": "+241", "flag_emoji": "🇬🇦", "currency_code": "XAF", "currency_symbol": "Fr"},
    {"name": "Gambia", "code": "GM", "phone_code": "+220", "flag_emoji": "🇬🇲", "currency_code": "GMD", "currency_symbol": "D"},
    {"name": "Georgia", "code": "GE", "phone_code": "+995", "flag_emoji": "🇬🇪", "currency_code": "GEL", "currency_symbol": "₾"},
    {"name": "Germany", "code": "DE", "phone_code": "+49", "flag_emoji": "🇩🇪", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Ghana", "code": "GH", "phone_code": "+233", "flag_emoji": "🇬🇭", "currency_code": "GHS", "currency_symbol": "₵"},
    {"name": "Greece", "code": "GR", "phone_code": "+30", "flag_emoji": "🇬🇷", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Guatemala", "code": "GT", "phone_code": "+502", "flag_emoji": "🇬🇹", "currency_code": "GTQ", "currency_symbol": "Q"},
    {"name": "Guinea", "code": "GN", "phone_code": "+224", "flag_emoji": "🇬🇳", "currency_code": "GNF", "currency_symbol": "Fr"},
    {"name": "Haiti", "code": "HT", "phone_code": "+509", "flag_emoji": "🇭🇹", "currency_code": "HTG", "currency_symbol": "G"},
    {"name": "Honduras", "code": "HN", "phone_code": "+504", "flag_emoji": "🇭🇳", "currency_code": "HNL", "currency_symbol": "L"},
    {"name": "Hungary", "code": "HU", "phone_code": "+36", "flag_emoji": "🇭🇺", "currency_code": "HUF", "currency_symbol": "Ft"},
    {"name": "Iceland", "code": "IS", "phone_code": "+354", "flag_emoji": "🇮🇸", "currency_code": "ISK", "currency_symbol": "kr"},
    {"name": "India", "code": "IN", "phone_code": "+91", "flag_emoji": "🇮🇳", "currency_code": "INR", "currency_symbol": "₹"},
    {"name": "Indonesia", "code": "ID", "phone_code": "+62", "flag_emoji": "🇮🇩", "currency_code": "IDR", "currency_symbol": "Rp"},
    {"name": "Iran", "code": "IR", "phone_code": "+98", "flag_emoji": "🇮🇷", "currency_code": "IRR", "currency_symbol": "﷼"},
    {"name": "Iraq", "code": "IQ", "phone_code": "+964", "flag_emoji": "🇮🇶", "currency_code": "IQD", "currency_symbol": "ع.د"},
    {"name": "Ireland", "code": "IE", "phone_code": "+353", "flag_emoji": "🇮🇪", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Israel", "code": "IL", "phone_code": "+972", "flag_emoji": "🇮🇱", "currency_code": "ILS", "currency_symbol": "₪"},
    {"name": "Italy", "code": "IT", "phone_code": "+39", "flag_emoji": "🇮🇹", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Ivory Coast", "code": "CI", "phone_code": "+225", "flag_emoji": "🇨🇮", "currency_code": "XOF", "currency_symbol": "Fr"},
    {"name": "Jamaica", "code": "JM", "phone_code": "+1-876", "flag_emoji": "🇯🇲", "currency_code": "JMD", "currency_symbol": "$"},
    {"name": "Japan", "code": "JP", "phone_code": "+81", "flag_emoji": "🇯🇵", "currency_code": "JPY", "currency_symbol": "¥"},
    {"name": "Jordan", "code": "JO", "phone_code": "+962", "flag_emoji": "🇯🇴", "currency_code": "JOD", "currency_symbol": "د.ا"},
    {"name": "Kazakhstan", "code": "KZ", "phone_code": "+7", "flag_emoji": "🇰🇿", "currency_code": "KZT", "currency_symbol": "₸"},
    {"name": "Kenya", "code": "KE", "phone_code": "+254", "flag_emoji": "🇰🇪", "currency_code": "KES", "currency_symbol": "KSh"},
    {"name": "Kuwait", "code": "KW", "phone_code": "+965", "flag_emoji": "🇰🇼", "currency_code": "KWD", "currency_symbol": "د.ك"},
    {"name": "Kyrgyzstan", "code": "KG", "phone_code": "+996", "flag_emoji": "🇰🇬", "currency_code": "KGS", "currency_symbol": "лв"},
    {"name": "Laos", "code": "LA", "phone_code": "+856", "flag_emoji": "🇱🇦", "currency_code": "LAK", "currency_symbol": "₭"},
    {"name": "Latvia", "code": "LV", "phone_code": "+371", "flag_emoji": "🇱🇻", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Lebanon", "code": "LB", "phone_code": "+961", "flag_emoji": "🇱🇧", "currency_code": "LBP", "currency_symbol": "£"},
    {"name": "Lesotho", "code": "LS", "phone_code": "+266", "flag_emoji": "🇱🇸", "currency_code": "LSL", "currency_symbol": "L"},
    {"name": "Liberia", "code": "LR", "phone_code": "+231", "flag_emoji": "🇱🇷", "currency_code": "LRD", "currency_symbol": "$"},
    {"name": "Libya", "code": "LY", "phone_code": "+218", "flag_emoji": "🇱🇾", "currency_code": "LYD", "currency_symbol": "ل.د"},
    {"name": "Lithuania", "code": "LT", "phone_code": "+370", "flag_emoji": "🇱🇹", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Luxembourg", "code": "LU", "phone_code": "+352", "flag_emoji": "🇱🇺", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Madagascar", "code": "MG", "phone_code": "+261", "flag_emoji": "🇲🇬", "currency_code": "MGA", "currency_symbol": "Ar"},
    {"name": "Malawi", "code": "MW", "phone_code": "+265", "flag_emoji": "🇲🇼", "currency_code": "MWK", "currency_symbol": "MK"},
    {"name": "Malaysia", "code": "MY", "phone_code": "+60", "flag_emoji": "🇲🇾", "currency_code": "MYR", "currency_symbol": "RM"},
    {"name": "Mali", "code": "ML", "phone_code": "+223", "flag_emoji": "🇲🇱", "currency_code": "XOF", "currency_symbol": "Fr"},
    {"name": "Malta", "code": "MT", "phone_code": "+356", "flag_emoji": "🇲🇹", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Mauritania", "code": "MR", "phone_code": "+222", "flag_emoji": "🇲🇷", "currency_code": "MRU", "currency_symbol": "UM"},
    {"name": "Mauritius", "code": "MU", "phone_code": "+230", "flag_emoji": "🇲🇺", "currency_code": "MUR", "currency_symbol": "₨"},
    {"name": "Mexico", "code": "MX", "phone_code": "+52", "flag_emoji": "🇲🇽", "currency_code": "MXN", "currency_symbol": "$"},
    {"name": "Moldova", "code": "MD", "phone_code": "+373", "flag_emoji": "🇲🇩", "currency_code": "MDL", "currency_symbol": "L"},
    {"name": "Mongolia", "code": "MN", "phone_code": "+976", "flag_emoji": "🇲🇳", "currency_code": "MNT", "currency_symbol": "₮"},
    {"name": "Montenegro", "code": "ME", "phone_code": "+382", "flag_emoji": "🇲🇪", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Morocco", "code": "MA", "phone_code": "+212", "flag_emoji": "🇲🇦", "currency_code": "MAD", "currency_symbol": "د.م."},
    {"name": "Mozambique", "code": "MZ", "phone_code": "+258", "flag_emoji": "🇲🇿", "currency_code": "MZN", "currency_symbol": "MT"},
    {"name": "Myanmar", "code": "MM", "phone_code": "+95", "flag_emoji": "🇲🇲", "currency_code": "MMK", "currency_symbol": "K"},
    {"name": "Namibia", "code": "NA", "phone_code": "+264", "flag_emoji": "🇳🇦", "currency_code": "NAD", "currency_symbol": "$"},
    {"name": "Nepal", "code": "NP", "phone_code": "+977", "flag_emoji": "🇳🇵", "currency_code": "NPR", "currency_symbol": "₨"},
    {"name": "Netherlands", "code": "NL", "phone_code": "+31", "flag_emoji": "🇳🇱", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "New Zealand", "code": "NZ", "phone_code": "+64", "flag_emoji": "🇳🇿", "currency_code": "NZD", "currency_symbol": "$"},
    {"name": "Nicaragua", "code": "NI", "phone_code": "+505", "flag_emoji": "🇳🇮", "currency_code": "NIO", "currency_symbol": "C$"},
    {"name": "Niger", "code": "NE", "phone_code": "+227", "flag_emoji": "🇳🇪", "currency_code": "XOF", "currency_symbol": "Fr"},
    {"name": "Nigeria", "code": "NG", "phone_code": "+234", "flag_emoji": "🇳🇬", "currency_code": "NGN", "currency_symbol": "₦"},
    {"name": "North Korea", "code": "KP", "phone_code": "+850", "flag_emoji": "🇰🇵", "currency_code": "KPW", "currency_symbol": "₩"},
    {"name": "North Macedonia", "code": "MK", "phone_code": "+389", "flag_emoji": "🇲🇰", "currency_code": "MKD", "currency_symbol": "ден"},
    {"name": "Norway", "code": "NO", "phone_code": "+47", "flag_emoji": "🇳🇴", "currency_code": "NOK", "currency_symbol": "kr"},
    {"name": "Oman", "code": "OM", "phone_code": "+968", "flag_emoji": "🇴🇲", "currency_code": "OMR", "currency_symbol": "﷼"},
    {"name": "Pakistan", "code": "PK", "phone_code": "+92", "flag_emoji": "🇵🇰", "currency_code": "PKR", "currency_symbol": "₨"},
    {"name": "Panama", "code": "PA", "phone_code": "+507", "flag_emoji": "🇵🇦", "currency_code": "PAB", "currency_symbol": "B/."},
    {"name": "Paraguay", "code": "PY", "phone_code": "+595", "flag_emoji": "🇵🇾", "currency_code": "PYG", "currency_symbol": "₲"},
    {"name": "Peru", "code": "PE", "phone_code": "+51", "flag_emoji": "🇵🇪", "currency_code": "PEN", "currency_symbol": "S/."},
    {"name": "Philippines", "code": "PH", "phone_code": "+63", "flag_emoji": "🇵🇭", "currency_code": "PHP", "currency_symbol": "₱"},
    {"name": "Poland", "code": "PL", "phone_code": "+48", "flag_emoji": "🇵🇱", "currency_code": "PLN", "currency_symbol": "zł"},
    {"name": "Portugal", "code": "PT", "phone_code": "+351", "flag_emoji": "🇵🇹", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Qatar", "code": "QA", "phone_code": "+974", "flag_emoji": "🇶🇦", "currency_code": "QAR", "currency_symbol": "﷼"},
    {"name": "Romania", "code": "RO", "phone_code": "+40", "flag_emoji": "🇷🇴", "currency_code": "RON", "currency_symbol": "lei"},
    {"name": "Russia", "code": "RU", "phone_code": "+7", "flag_emoji": "🇷🇺", "currency_code": "RUB", "currency_symbol": "₽"},
    {"name": "Rwanda", "code": "RW", "phone_code": "+250", "flag_emoji": "🇷🇼", "currency_code": "RWF", "currency_symbol": "Fr"},
    {"name": "Saudi Arabia", "code": "SA", "phone_code": "+966", "flag_emoji": "🇸🇦", "currency_code": "SAR", "currency_symbol": "﷼"},
    {"name": "Senegal", "code": "SN", "phone_code": "+221", "flag_emoji": "🇸🇳", "currency_code": "XOF", "currency_symbol": "Fr"},
    {"name": "Serbia", "code": "RS", "phone_code": "+381", "flag_emoji": "🇷🇸", "currency_code": "RSD", "currency_symbol": "din"},
    {"name": "Sierra Leone", "code": "SL", "phone_code": "+232", "flag_emoji": "🇸🇱", "currency_code": "SLL", "currency_symbol": "Le"},
    {"name": "Singapore", "code": "SG", "phone_code": "+65", "flag_emoji": "🇸🇬", "currency_code": "SGD", "currency_symbol": "$"},
    {"name": "Slovakia", "code": "SK", "phone_code": "+421", "flag_emoji": "🇸🇰", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Slovenia", "code": "SI", "phone_code": "+386", "flag_emoji": "🇸🇮", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Somalia", "code": "SO", "phone_code": "+252", "flag_emoji": "🇸🇴", "currency_code": "SOS", "currency_symbol": "Sh"},
    {"name": "South Africa", "code": "ZA", "phone_code": "+27", "flag_emoji": "🇿🇦", "currency_code": "ZAR", "currency_symbol": "R"},
    {"name": "South Korea", "code": "KR", "phone_code": "+82", "flag_emoji": "🇰🇷", "currency_code": "KRW", "currency_symbol": "₩"},
    {"name": "South Sudan", "code": "SS", "phone_code": "+211", "flag_emoji": "🇸🇸", "currency_code": "SSP", "currency_symbol": "£"},
    {"name": "Spain", "code": "ES", "phone_code": "+34", "flag_emoji": "🇪🇸", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Sri Lanka", "code": "LK", "phone_code": "+94", "flag_emoji": "🇱🇰", "currency_code": "LKR", "currency_symbol": "₨"},
    {"name": "Sudan", "code": "SD", "phone_code": "+249", "flag_emoji": "🇸🇩", "currency_code": "SDG", "currency_symbol": "£"},
    {"name": "Sweden", "code": "SE", "phone_code": "+46", "flag_emoji": "🇸🇪", "currency_code": "SEK", "currency_symbol": "kr"},
    {"name": "Switzerland", "code": "CH", "phone_code": "+41", "flag_emoji": "🇨🇭", "currency_code": "CHF", "currency_symbol": "Fr"},
    {"name": "Syria", "code": "SY", "phone_code": "+963", "flag_emoji": "🇸🇾", "currency_code": "SYP", "currency_symbol": "£"},
    {"name": "Taiwan", "code": "TW", "phone_code": "+886", "flag_emoji": "🇹🇼", "currency_code": "TWD", "currency_symbol": "$"},
    {"name": "Tajikistan", "code": "TJ", "phone_code": "+992", "flag_emoji": "🇹🇯", "currency_code": "TJS", "currency_symbol": "SM"},
    {"name": "Tanzania", "code": "TZ", "phone_code": "+255", "flag_emoji": "🇹🇿", "currency_code": "TZS", "currency_symbol": "Sh"},
    {"name": "Thailand", "code": "TH", "phone_code": "+66", "flag_emoji": "🇹🇭", "currency_code": "THB", "currency_symbol": "฿"},
    {"name": "Togo", "code": "TG", "phone_code": "+228", "flag_emoji": "🇹🇬", "currency_code": "XOF", "currency_symbol": "Fr"},
    {"name": "Trinidad and Tobago", "code": "TT", "phone_code": "+1-868", "flag_emoji": "🇹🇹", "currency_code": "TTD", "currency_symbol": "$"},
    {"name": "Tunisia", "code": "TN", "phone_code": "+216", "flag_emoji": "🇹🇳", "currency_code": "TND", "currency_symbol": "د.ت"},
    {"name": "Turkey", "code": "TR", "phone_code": "+90", "flag_emoji": "🇹🇷", "currency_code": "TRY", "currency_symbol": "₺"},
    {"name": "Turkmenistan", "code": "TM", "phone_code": "+993", "flag_emoji": "🇹🇲", "currency_code": "TMT", "currency_symbol": "T"},
    {"name": "Uganda", "code": "UG", "phone_code": "+256", "flag_emoji": "🇺🇬", "currency_code": "UGX", "currency_symbol": "Sh"},
    {"name": "Ukraine", "code": "UA", "phone_code": "+380", "flag_emoji": "🇺🇦", "currency_code": "UAH", "currency_symbol": "₴"},
    {"name": "United Arab Emirates", "code": "AE", "phone_code": "+971", "flag_emoji": "🇦🇪", "currency_code": "AED", "currency_symbol": "د.إ"},
    {"name": "United Kingdom", "code": "GB", "phone_code": "+44", "flag_emoji": "🇬🇧", "currency_code": "GBP", "currency_symbol": "£"},
    {"name": "United States", "code": "US", "phone_code": "+1", "flag_emoji": "🇺🇸", "currency_code": "USD", "currency_symbol": "$"},
    {"name": "Uruguay", "code": "UY", "phone_code": "+598", "flag_emoji": "🇺🇾", "currency_code": "UYU", "currency_symbol": "$"},
    {"name": "Uzbekistan", "code": "UZ", "phone_code": "+998", "flag_emoji": "🇺🇿", "currency_code": "UZS", "currency_symbol": "лв"},
    {"name": "Venezuela", "code": "VE", "phone_code": "+58", "flag_emoji": "🇻🇪", "currency_code": "VES", "currency_symbol": "Bs.S"},
    {"name": "Vietnam", "code": "VN", "phone_code": "+84", "flag_emoji": "🇻🇳", "currency_code": "VND", "currency_symbol": "₫"},
    {"name": "Yemen", "code": "YE", "phone_code": "+967", "flag_emoji": "🇾🇪", "currency_code": "YER", "currency_symbol": "﷼"},
    {"name": "Zambia", "code": "ZM", "phone_code": "+260", "flag_emoji": "🇿🇲", "currency_code": "ZMW", "currency_symbol": "ZK"},
    {"name": "Zimbabwe", "code": "ZW", "phone_code": "+263", "flag_emoji": "🇿🇼", "currency_code": "ZWL", "currency_symbol": "$"},
    {"name": "Andorra", "code": "AD", "phone_code": "+376", "flag_emoji": "🇦🇩", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Angola", "code": "AO", "phone_code": "+244", "flag_emoji": "🇦🇴", "currency_code": "AOA", "currency_symbol": "Kz"},
    {"name": "Antigua and Barbuda", "code": "AG", "phone_code": "+1-268", "flag_emoji": "🇦🇬", "currency_code": "XCD", "currency_symbol": "$"},
    {"name": "Bahamas", "code": "BS", "phone_code": "+1-242", "flag_emoji": "🇧🇸", "currency_code": "BSD", "currency_symbol": "$"},
    {"name": "Barbados", "code": "BB", "phone_code": "+1-246", "flag_emoji": "🇧🇧", "currency_code": "BBD", "currency_symbol": "$"},
    {"name": "Belize", "code": "BZ", "phone_code": "+501", "flag_emoji": "🇧🇿", "currency_code": "BZD", "currency_symbol": "$"},
    {"name": "Bhutan", "code": "BT", "phone_code": "+975", "flag_emoji": "🇧🇹", "currency_code": "BTN", "currency_symbol": "Nu"},
    {"name": "Cape Verde", "code": "CV", "phone_code": "+238", "flag_emoji": "🇨🇻", "currency_code": "CVE", "currency_symbol": "$"},
    {"name": "Central African Republic", "code": "CF", "phone_code": "+236", "flag_emoji": "🇨🇫", "currency_code": "XAF", "currency_symbol": "Fr"},
    {"name": "Comoros", "code": "KM", "phone_code": "+269", "flag_emoji": "🇰🇲", "currency_code": "KMF", "currency_symbol": "Fr"},
    {"name": "Djibouti", "code": "DJ", "phone_code": "+253", "flag_emoji": "🇩🇯", "currency_code": "DJF", "currency_symbol": "Fr"},
    {"name": "Dominica", "code": "DM", "phone_code": "+1-767", "flag_emoji": "🇩🇲", "currency_code": "XCD", "currency_symbol": "$"},
    {"name": "Equatorial Guinea", "code": "GQ", "phone_code": "+240", "flag_emoji": "🇬🇶", "currency_code": "XAF", "currency_symbol": "Fr"},
    {"name": "Fiji", "code": "FJ", "phone_code": "+679", "flag_emoji": "🇫🇯", "currency_code": "FJD", "currency_symbol": "$"},
    {"name": "Grenada", "code": "GD", "phone_code": "+1-473", "flag_emoji": "🇬🇩", "currency_code": "XCD", "currency_symbol": "$"},
    {"name": "Guinea-Bissau", "code": "GW", "phone_code": "+245", "flag_emoji": "🇬🇼", "currency_code": "XOF", "currency_symbol": "Fr"},
    {"name": "Guyana", "code": "GY", "phone_code": "+592", "flag_emoji": "🇬🇾", "currency_code": "GYD", "currency_symbol": "$"},
    {"name": "Holy See", "code": "VA", "phone_code": "+379", "flag_emoji": "🇻🇦", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Kiribati", "code": "KI", "phone_code": "+686", "flag_emoji": "🇰🇮", "currency_code": "AUD", "currency_symbol": "$"},
    {"name": "Kosovo", "code": "XK", "phone_code": "+383", "flag_emoji": "🇽🇰", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Liechtenstein", "code": "LI", "phone_code": "+423", "flag_emoji": "🇱🇮", "currency_code": "CHF", "currency_symbol": "Fr"},
    {"name": "Maldives", "code": "MV", "phone_code": "+960", "flag_emoji": "🇲🇻", "currency_code": "MVR", "currency_symbol": "Rf"},
    {"name": "Marshall Islands", "code": "MH", "phone_code": "+692", "flag_emoji": "🇲🇭", "currency_code": "USD", "currency_symbol": "$"},
    {"name": "Micronesia", "code": "FM", "phone_code": "+691", "flag_emoji": "🇫🇲", "currency_code": "USD", "currency_symbol": "$"},
    {"name": "Monaco", "code": "MC", "phone_code": "+377", "flag_emoji": "🇲🇨", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Nauru", "code": "NR", "phone_code": "+674", "flag_emoji": "🇳🇷", "currency_code": "AUD", "currency_symbol": "$"},
    {"name": "Palau", "code": "PW", "phone_code": "+680", "flag_emoji": "🇵🇼", "currency_code": "USD", "currency_symbol": "$"},
    {"name": "Palestine", "code": "PS", "phone_code": "+970", "flag_emoji": "🇵🇸", "currency_code": "ILS", "currency_symbol": "₪"},
    {"name": "Papua New Guinea", "code": "PG", "phone_code": "+675", "flag_emoji": "🇵🇬", "currency_code": "PGK", "currency_symbol": "K"},
    {"name": "Saint Kitts and Nevis", "code": "KN", "phone_code": "+1-869", "flag_emoji": "🇰🇳", "currency_code": "XCD", "currency_symbol": "$"},
    {"name": "Saint Lucia", "code": "LC", "phone_code": "+1-758", "flag_emoji": "🇱🇨", "currency_code": "XCD", "currency_symbol": "$"},
    {"name": "Saint Vincent and the Grenadines", "code": "VC", "phone_code": "+1-784", "flag_emoji": "🇻🇨", "currency_code": "XCD", "currency_symbol": "$"},
    {"name": "Samoa", "code": "WS", "phone_code": "+685", "flag_emoji": "🇼🇸", "currency_code": "WST", "currency_symbol": "T"},
    {"name": "San Marino", "code": "SM", "phone_code": "+378", "flag_emoji": "🇸🇲", "currency_code": "EUR", "currency_symbol": "€"},
    {"name": "Sao Tome and Principe", "code": "ST", "phone_code": "+239", "flag_emoji": "🇸🇹", "currency_code": "STN", "currency_symbol": "Db"},
    {"name": "Seychelles", "code": "SC", "phone_code": "+248", "flag_emoji": "🇸🇨", "currency_code": "SCR", "currency_symbol": "₨"},
    {"name": "Solomon Islands", "code": "SB", "phone_code": "+677", "flag_emoji": "🇸🇧", "currency_code": "SBD", "currency_symbol": "$"},
    {"name": "Suriname", "code": "SR", "phone_code": "+597", "flag_emoji": "🇸🇷", "currency_code": "SRD", "currency_symbol": "$"},
    {"name": "Timor-Leste", "code": "TL", "phone_code": "+670", "flag_emoji": "🇹🇱", "currency_code": "USD", "currency_symbol": "$"},
    {"name": "Tonga", "code": "TO", "phone_code": "+676", "flag_emoji": "🇹🇴", "currency_code": "TOP", "currency_symbol": "T$"},
    {"name": "Tuvalu", "code": "TV", "phone_code": "+688", "flag_emoji": "🇹🇻", "currency_code": "AUD", "currency_symbol": "$"},
    {"name": "Vanuatu", "code": "VU", "phone_code": "+678", "flag_emoji": "🇻🇺", "currency_code": "VUV", "currency_symbol": "Vt"},
]


class Command(BaseCommand):
    help = "Seed the Country table with all world countries."

    def handle(self, *args, **kwargs):
        # Import here to avoid app registry issues
        from django.apps import apps
        Country = apps.get_model('AUTH', 'Country')  # change 'Account' to your app name if different

        created_count = 0
        updated_count = 0

        for country_data in COUNTRIES:
            obj, created = Country.objects.update_or_create(
                code=country_data['code'],
                defaults={
                    'name': country_data['name'],
                    'phone_code': country_data['phone_code'],
                    'flag_emoji': country_data['flag_emoji'],
                    'currency_code': country_data['currency_code'],
                    'currency_symbol': country_data['currency_symbol'],
                    'is_active': True,
                }
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Done. {created_count} countries created, {updated_count} updated."
            )
        )