# Generated by Django 6.0.1 on 2026-01-26 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns this brand', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ANALYTICS.brand')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creators',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_creator_name')],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platforms',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='idx_platform_slug'), models.Index(fields=['is_active'], name='idx_platform_active')],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Content', max_length=500)),
                ('external_id', models.CharField(blank=True, help_text='Platform-specific content ID', max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='ANALYTICS.campaign')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='ANALYTICS.creator')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='ANALYTICS.platform')),
            ],
            options={
                'db_table': 'content',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_code', models.CharField(blank=True, help_text='Unique short code for the tracking link', max_length=50, null=True, unique=True)),
                ('destination_url', models.URLField(help_text='The URL where the tracking link redirects', max_length=2048)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='ANALYTICS.campaign')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_links', to='ANALYTICS.content')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='ANALYTICS.creator')),
            ],
            options={
                'db_table': 'tracking_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the event', primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('impression', 'Impression'), ('click', 'Click'), ('like', 'Like'), ('share', 'Share'), ('comment', 'Comment'), ('signup', 'Sign Up'), ('login', 'Login'), ('purchase', 'Purchase'), ('add_to_cart', 'Add to Cart'), ('refund', 'Refund'), ('download', 'Download'), ('search', 'Search'), ('custom', 'Custom')], db_index=True, help_text='Type of analytics event (static choices for MVP)', max_length=50)),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='When the event actually occurred (may differ from created_at)')),
                ('external_event_id', models.CharField(blank=True, db_index=True, help_text='External system event ID for cross-system tracking', max_length=255, null=True)),
                ('dedupe_hash', models.CharField(blank=True, help_text='Hash for deduplication - unique constraint prevents duplicate events', max_length=64, null=True, unique=True)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text="Event-specific metrics (e.g., {'clicks': 10, 'revenue': 100.50})", null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text="Additional metadata (e.g., {'user_agent': '...', 'ip': '...'})", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event was inserted into the database')),
                ('brand', models.ForeignKey(blank=True, help_text='Brand associated with event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='ANALYTICS.brand')),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign associated with event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='ANALYTICS.campaign')),
                ('content', models.ForeignKey(blank=True, help_text='Content associated with event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='ANALYTICS.content')),
                ('creator', models.ForeignKey(blank=True, help_text='Creator associated with event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='ANALYTICS.creator')),
                ('platform', models.ForeignKey(blank=True, help_text='Platform where event occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='ANALYTICS.platform')),
                ('link', models.ForeignKey(blank=True, help_text='Tracking link associated with event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='ANALYTICS.trackinglink')),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'db_table': 'analytics_events',
                'ordering': ['-occurred_at'],
                'permissions': [('cannot_update', 'Cannot update analytics events')],
            },
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['owner', 'name'], name='idx_brand_owner_name'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['brand', '-created_at'], name='idx_campaign_brand_created'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='idx_campaign_active'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['platform', 'external_id'], name='idx_content_platform_extid'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['campaign', '-published_at'], name='idx_content_campaign_pub'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['creator', '-published_at'], name='idx_content_creator_pub'),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('platform', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='trackinglink',
            index=models.Index(fields=['short_code'], name='idx_link_short_code'),
        ),
        migrations.AddIndex(
            model_name='trackinglink',
            index=models.Index(fields=['campaign', '-created_at'], name='idx_link_campaign_created'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='idx_type_occurred'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['-created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['campaign', 'occurred_at'], name='idx_evt_campaign_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['creator', 'occurred_at'], name='idx_evt_creator_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['content', 'occurred_at'], name='idx_evt_content_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['brand', 'occurred_at'], name='idx_evt_brand_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['platform', 'occurred_at'], name='idx_evt_platform_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['link', 'occurred_at'], name='idx_evt_link_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['dedupe_hash'], name='idx_evt_dedupe_hash'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['external_event_id'], name='idx_evt_external_id'),
        ),
    ]
