# Generated by Django 6.0.1 on 2026-02-03 21:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANALYTICS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(choices=[('creator_fee', 'Creator Fee'), ('ad_spend', 'Paid Advertising'), ('production', 'Content Production'), ('influencer_gifting', 'Product Gifting'), ('platform_fees', 'Platform Fees'), ('agency_fees', 'Agency Fees'), ('software', 'Software/Tools'), ('other', 'Other')], db_index=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('expense_date', models.DateField(db_index=True)),
                ('receipt_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaign_expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ContentSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(db_index=True, help_text='When these metrics were captured')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('saves_count', models.IntegerField(default=0)),
                ('views_count', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0, help_text='Unique users who saw the content')),
                ('impressions', models.BigIntegerField(default=0, help_text='Total times content was displayed')),
                ('engagement_rate', models.FloatField(blank=True, help_text='Engagement rate at time of capture', null=True)),
                ('platform_metrics', models.JSONField(blank=True, default=dict, help_text='Platform-specific metrics:\n        Instagram: {"profile_visits": 200, "website_clicks": 50}\n        YouTube: {"watch_time_hours": 1200, "avg_view_duration": 180}\n        TikTok: {"completion_rate": 0.65, "average_watch_time": 12}\n        ')),
                ('likes_delta', models.IntegerField(default=0, help_text='Change in likes since last snapshot')),
                ('comments_delta', models.IntegerField(default=0)),
                ('shares_delta', models.IntegerField(default=0)),
                ('views_delta', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contracted_amount', models.DecimalField(decimal_places=2, help_text='Total amount agreed to pay creator', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid to date', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid in Full'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('payment_completed_date', models.DateField(blank=True, null=True)),
                ('deliverable_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('deliverables', models.JSONField(blank=True, default=dict, help_text="Expected deliverables: {'instagram_posts': 3, 'stories': 5, 'reels': 1}")),
                ('deliverables_completed', models.JSONField(blank=True, default=dict, help_text='Completed deliverables count')),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creator_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkDailyStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_clicks', models.IntegerField(default=0, help_text='Total number of clicks')),
                ('unique_clicks', models.IntegerField(default=0, help_text='Unique clicks (by session/fingerprint)')),
                ('conversions', models.IntegerField(default=0, help_text='Number of conversions attributed to this link')),
                ('conversion_rate', models.FloatField(blank=True, help_text='Conversion rate (conversions / unique_clicks)', null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue attributed to this link', max_digits=12)),
                ('geo_data', models.JSONField(blank=True, default=dict, help_text="Geographic breakdown: {'US': 100, 'UK': 50}")),
                ('device_data', models.JSONField(blank=True, default=dict, help_text="Device breakdown: {'mobile': 150, 'desktop': 50}")),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'link_daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='conversion_attributed_to_link',
            field=models.ForeignKey(blank=True, help_text='Link that gets attribution credit for this conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_conversions', to='ANALYTICS.trackinglink'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='conversion_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Revenue value for purchase/conversion events', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code (USD, EUR, GBP, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount spent to date (calculated from expenses)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total allocated budget for this campaign', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, help_text='Campaign identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='utm_content',
            field=models.CharField(blank=True, help_text='Content variant (e.g., story, post, bio_link)', max_length=255),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='utm_medium',
            field=models.CharField(blank=True, help_text='Marketing medium (e.g., social, influencer)', max_length=255),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, help_text='Traffic source (e.g., instagram, youtube)', max_length=255),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='utm_term',
            field=models.CharField(blank=True, help_text='Paid search keywords', max_length=255),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['conversion_attributed_to_link', 'occurred_at'], name='idx_evt_conversion_attr'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_campaign_dates'),
        ),
        migrations.AddIndex(
            model_name='trackinglink',
            index=models.Index(fields=['utm_source', 'utm_campaign'], name='idx_link_utm'),
        ),
        migrations.AddField(
            model_name='campaignexpense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignexpense',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='ANALYTICS.campaign'),
        ),
        migrations.AddField(
            model_name='campaignexpense',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='If expense is for a specific creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='ANALYTICS.creator'),
        ),
        migrations.AddField(
            model_name='contentsnapshot',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='ANALYTICS.content'),
        ),
        migrations.AddField(
            model_name='creatorcontract',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_contracts', to='ANALYTICS.campaign'),
        ),
        migrations.AddField(
            model_name='creatorcontract',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='ANALYTICS.creator'),
        ),
        migrations.AddField(
            model_name='campaignexpense',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Link to creator contract if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='ANALYTICS.creatorcontract'),
        ),
        migrations.AddField(
            model_name='linkdailystat',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='ANALYTICS.trackinglink'),
        ),
        migrations.AddIndex(
            model_name='contentsnapshot',
            index=models.Index(fields=['content', '-captured_at'], name='idx_snapshot_content_time'),
        ),
        migrations.AddIndex(
            model_name='contentsnapshot',
            index=models.Index(fields=['captured_at'], name='idx_snapshot_captured_at'),
        ),
        migrations.AlterUniqueTogether(
            name='contentsnapshot',
            unique_together={('content', 'captured_at')},
        ),
        migrations.AddIndex(
            model_name='creatorcontract',
            index=models.Index(fields=['campaign', 'creator'], name='idx_contract_campaign_creator'),
        ),
        migrations.AddIndex(
            model_name='creatorcontract',
            index=models.Index(fields=['payment_status'], name='idx_contract_payment_status'),
        ),
        migrations.AddIndex(
            model_name='creatorcontract',
            index=models.Index(fields=['deliverable_status'], name='idx_contract_deliv_status'),
        ),
        migrations.AlterUniqueTogether(
            name='creatorcontract',
            unique_together={('campaign', 'creator')},
        ),
        migrations.AddIndex(
            model_name='campaignexpense',
            index=models.Index(fields=['campaign', '-expense_date'], name='idx_expense_campaign_date'),
        ),
        migrations.AddIndex(
            model_name='campaignexpense',
            index=models.Index(fields=['expense_type', '-expense_date'], name='idx_expense_type_date'),
        ),
        migrations.AddIndex(
            model_name='campaignexpense',
            index=models.Index(fields=['creator', '-expense_date'], name='idx_expense_creator_date'),
        ),
        migrations.AddIndex(
            model_name='campaignexpense',
            index=models.Index(fields=['is_approved'], name='idx_expense_approved'),
        ),
        migrations.AddIndex(
            model_name='linkdailystat',
            index=models.Index(fields=['link', '-date'], name='idx_linkstat_link_date'),
        ),
        migrations.AddIndex(
            model_name='linkdailystat',
            index=models.Index(fields=['date'], name='idx_linkstat_date'),
        ),
        migrations.AlterUniqueTogether(
            name='linkdailystat',
            unique_together={('link', 'date')},
        ),
    ]
