# Generated by Django 6.0.1 on 2026-02-04 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANALYTICS', '0002_campaignexpense_contentsnapshot_creatorcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkdailystat',
            name='unique_clicks',
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Session identifier (browser session, app session).\n        Used for sessionized analytics. Expires after inactivity period.\n        Example: Session UUID, expires after 30min inactivity', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stable visitor identifier (cookie/fingerprint/device_id).\n        Used for unique user counting. Should be consistent across sessions.\n        Example: UUID from cookie, hashed fingerprint, authenticated user_id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkdailystat',
            name='unique_sessions',
            field=models.IntegerField(default=0, help_text='Unique sessions (distinct session_id)'),
        ),
        migrations.AddField(
            model_name='linkdailystat',
            name='unique_users',
            field=models.IntegerField(default=0, help_text='Unique authenticated users (distinct user_id)'),
        ),
        migrations.AddField(
            model_name='linkdailystat',
            name='unique_visitors',
            field=models.IntegerField(default=0, help_text='Unique visitors (distinct visitor_id) - most accurate unique count'),
        ),
        migrations.AlterField(
            model_name='linkdailystat',
            name='conversion_rate',
            field=models.FloatField(blank=True, help_text='Conversion rate (conversions / unique_visitors * 100)', null=True),
        ),
        migrations.AlterField(
            model_name='linkdailystat',
            name='total_clicks',
            field=models.IntegerField(default=0, help_text='Total number of clicks (all events)'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['visitor_id', 'occurred_at'], name='idx_evt_visitor_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_id', 'occurred_at'], name='idx_evt_session_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'occurred_at'], name='idx_evt_user_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['link', 'visitor_id'], name='idx_evt_link_visitor'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['campaign', 'visitor_id'], name='idx_evt_campaign_visitor'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['content', 'visitor_id'], name='idx_evt_content_visitor'),
        ),
    ]
