# Generated by Django 5.2.11 on 2026-02-15 13:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANALYTICS', '0003_remove_linkdailystat_unique_clicks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDailyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('video_views', models.BigIntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('total_comments', models.BigIntegerField(default=0)),
                ('total_shares', models.BigIntegerField(default=0)),
                ('total_saves', models.BigIntegerField(default=0)),
                ('total_engagements', models.BigIntegerField(default=0, help_text='Sum of likes + comments + shares + saves')),
                ('total_clicks', models.BigIntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('unique_sessions', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('engagement_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('budget_spent_today', models.DecimalField(decimal_places=2, default=0, help_text='Expenses approved on this day', max_digits=12)),
                ('cpc', models.DecimalField(blank=True, decimal_places=4, help_text='Cost per click (cumulative campaign budget / total clicks)', max_digits=12, null=True)),
                ('cpm', models.DecimalField(blank=True, decimal_places=4, help_text='Cost per 1000 impressions', max_digits=12, null=True)),
                ('cpe', models.DecimalField(blank=True, decimal_places=4, help_text='Cost per engagement', max_digits=12, null=True)),
                ('content_posted', models.IntegerField(default=0, help_text='Number of content items posted this day')),
                ('active_creators', models.IntegerField(default=0, help_text='Number of creators who posted content this day')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='ANALYTICS.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Daily Stat',
                'verbose_name_plural': 'Campaign Daily Stats',
                'db_table': 'campaign_daily_stats',
                'ordering': ['-date', 'campaign'],
                'indexes': [models.Index(fields=['campaign', 'date'], name='campaign_da_campaig_9c79a4_idx'), models.Index(fields=['date', 'campaign'], name='campaign_da_date_b005da_idx')],
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ContentDailyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('video_views', models.BigIntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('total_comments', models.BigIntegerField(default=0)),
                ('total_shares', models.BigIntegerField(default=0)),
                ('total_saves', models.BigIntegerField(default=0)),
                ('total_engagements', models.BigIntegerField(default=0, help_text='Sum of likes + comments + shares + saves')),
                ('total_clicks', models.BigIntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('unique_sessions', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('engagement_rate', models.FloatField(blank=True, help_text='Engagement rate percentage', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('video_completion_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('avg_watch_time', models.FloatField(blank=True, help_text='Average watch time in seconds', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='ANALYTICS.content')),
            ],
            options={
                'verbose_name': 'Content Daily Stat',
                'verbose_name_plural': 'Content Daily Stats',
                'db_table': 'content_daily_stats',
                'ordering': ['-date', 'content'],
                'indexes': [models.Index(fields=['content', 'date'], name='content_dai_content_0ee505_idx'), models.Index(fields=['date', 'content'], name='content_dai_date_101df5_idx')],
                'unique_together': {('content', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CreatorDailyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('video_views', models.BigIntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('total_comments', models.BigIntegerField(default=0)),
                ('total_shares', models.BigIntegerField(default=0)),
                ('total_saves', models.BigIntegerField(default=0)),
                ('total_engagements', models.BigIntegerField(default=0, help_text='Sum of likes + comments + shares + saves')),
                ('total_clicks', models.BigIntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('unique_sessions', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('engagement_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('content_posted', models.IntegerField(default=0, help_text='Number of content items posted this day')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Optional: stats per creator per campaign', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_daily_stats', to='ANALYTICS.campaign')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='ANALYTICS.creator')),
            ],
            options={
                'verbose_name': 'Creator Daily Stat',
                'verbose_name_plural': 'Creator Daily Stats',
                'db_table': 'creator_daily_stats',
                'ordering': ['-date', 'creator'],
                'indexes': [models.Index(fields=['creator', 'date'], name='creator_dai_creator_f14a87_idx'), models.Index(fields=['creator', 'campaign', 'date'], name='creator_dai_creator_9e5d92_idx'), models.Index(fields=['date', 'creator'], name='creator_dai_date_82c466_idx')],
                'unique_together': {('creator', 'date', 'campaign')},
            },
        ),
    ]
