# Generated by Django 5.2.11 on 2026-02-06 09:52

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('SOCIAL_INTELLIGENCE', '0001_initial'), ('SOCIAL_INTELLIGENCE', '0002_alter_alert_id_alter_entitycompetitor_id_and_more')]

    dependencies = [
        ('ANALYTICS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, help_text='The actual keyword/phrase/hashtag to detect', max_length=255)),
                ('keyword_type', models.CharField(choices=[('hashtag', 'Hashtag'), ('phrase', 'Phrase'), ('handle', 'Handle'), ('exact_match', 'Exact Match'), ('regex', 'Regex Pattern')], db_index=True, max_length=50)),
                ('match_rule', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('regex', 'Regular Expression'), ('fuzzy', 'Fuzzy Match')], default='contains', max_length=50)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority keywords matched first')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entity Keyword',
                'verbose_name_plural': 'Entity Keywords',
                'db_table': 'entity_keywords',
                'ordering': ['-priority', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_post_id', models.CharField(db_index=True, help_text='Platform-specific post ID (e.g., tweet ID, Instagram post ID)', max_length=255)),
                ('text', models.TextField(blank=True)),
                ('author_username', models.CharField(db_index=True, max_length=255)),
                ('author_display_name', models.CharField(blank=True, max_length=255)),
                ('author_profile_url', models.URLField(blank=True, max_length=500)),
                ('post_url', models.URLField(blank=True, max_length=500)),
                ('post_type', models.CharField(default='post', help_text='post, retweet, reply, story, reel, etc.', max_length=50)),
                ('language', models.CharField(blank=True, db_index=True, max_length=10)),
                ('has_image', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('media_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_content', models.ForeignKey(blank=True, help_text='Link if this mention is actually campaign content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_mentions', to='ANALYTICS.platform')),
                ('creator', models.ForeignKey(blank=True, help_text='Link to Nexora creator if author is known', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='ANALYTICS.creator')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='ANALYTICS.platform')),
            ],
            options={
                'verbose_name': 'Mention',
                'verbose_name_plural': 'Mentions',
                'db_table': 'mentions',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MentionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(db_index=True, max_length=255)),
                ('topic_category', models.CharField(blank=True, help_text='Broader category this topic belongs to', max_length=100)),
                ('relevance_score', models.FloatField(help_text='How relevant this topic is to the mention', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('topic_metadata', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='SOCIAL_INTELLIGENCE.mention')),
            ],
            options={
                'verbose_name': 'Mention Topic',
                'verbose_name_plural': 'Mention Topics',
                'db_table': 'mention_topics',
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='TrackedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('entity_type', models.CharField(choices=[('brand', 'Brand'), ('person', 'Person'), ('product', 'Product'), ('topic', 'Topic'), ('campaign', 'Campaign'), ('competitor', 'Competitor')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tracking_ended_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Link to Nexora brand if tracking a brand', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_entities', to='ANALYTICS.brand')),
                ('campaign', models.ForeignKey(blank=True, help_text='Link to Nexora campaign if tracking a campaign', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_entities', to='ANALYTICS.campaign')),
                ('creator', models.ForeignKey(blank=True, help_text='Link to Nexora creator if tracking a person/influencer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_entities', to='ANALYTICS.creator')),
            ],
            options={
                'verbose_name': 'Tracked Entity',
                'verbose_name_plural': 'Tracked Entities',
                'db_table': 'tracked_entities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentionSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], db_index=True, max_length=20)),
                ('sentiment_score', models.FloatField(help_text='Sentiment score from -1.0 (negative) to 1.0 (positive)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(help_text='Confidence in sentiment analysis (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('analyzer', models.CharField(default='default', help_text='Which sentiment analyzer was used', max_length=100)),
                ('sentiment_context', models.TextField(blank=True, help_text='Specific text that influenced sentiment')),
                ('analysis_metadata', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='SOCIAL_INTELLIGENCE.mention')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='SOCIAL_INTELLIGENCE.trackedentity')),
            ],
            options={
                'verbose_name': 'Mention Sentiment',
                'verbose_name_plural': 'Mention Sentiments',
                'db_table': 'mention_sentiment',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='MentionEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=1.0, help_text='Confidence score of the match (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('match_context', models.TextField(blank=True, help_text='Text snippet where match was found')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword_matched', models.ForeignKey(blank=True, help_text='Which keyword triggered this detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_mentions', to='SOCIAL_INTELLIGENCE.entitykeyword')),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_entities', to='SOCIAL_INTELLIGENCE.mention')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='SOCIAL_INTELLIGENCE.trackedentity')),
            ],
            options={
                'verbose_name': 'Mention Entity',
                'verbose_name_plural': 'Mention Entities',
                'db_table': 'mention_entities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('mention_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('trending_score', models.FloatField(default=0.0, help_text='Calculated trending score')),
                ('growth_rate', models.FloatField(default=0.0, help_text='Rate of growth in mentions')),
                ('keyword_type', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_keywords', to='ANALYTICS.platform')),
                ('entity', models.ForeignKey(blank=True, help_text='Entity this keyword is associated with (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_keywords', to='SOCIAL_INTELLIGENCE.trackedentity')),
            ],
            options={
                'verbose_name': 'Extracted Keyword',
                'verbose_name_plural': 'Extracted Keywords',
                'db_table': 'extracted_keywords',
                'ordering': ['-trending_score', '-mention_count'],
            },
        ),
        migrations.AddField(
            model_name='entitykeyword',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='SOCIAL_INTELLIGENCE.trackedentity'),
        ),
        migrations.CreateModel(
            name='EntityDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_mentions', models.IntegerField(default=0)),
                ('unique_authors', models.IntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('total_comments', models.BigIntegerField(default=0)),
                ('total_shares', models.BigIntegerField(default=0)),
                ('total_views', models.BigIntegerField(default=0)),
                ('positive_mentions', models.IntegerField(default=0)),
                ('negative_mentions', models.IntegerField(default=0)),
                ('neutral_mentions', models.IntegerField(default=0)),
                ('avg_sentiment_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('estimated_reach', models.BigIntegerField(default=0)),
                ('estimated_impressions', models.BigIntegerField(default=0)),
                ('top_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Top trending keywords for this day', size=None)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(blank=True, help_text='Optional: stats per platform', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_daily_stats', to='ANALYTICS.platform')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='SOCIAL_INTELLIGENCE.trackedentity')),
            ],
            options={
                'verbose_name': 'Entity Daily Stat',
                'verbose_name_plural': 'Entity Daily Stats',
                'db_table': 'entity_daily_stats',
                'ordering': ['-date', 'entity'],
            },
        ),
        migrations.CreateModel(
            name='EntityCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(default='direct', help_text='direct, indirect, substitute, etc.', max_length=50)),
                ('priority', models.IntegerField(default=0, help_text='Priority/importance of this competitor')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competing_with', to='SOCIAL_INTELLIGENCE.trackedentity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='SOCIAL_INTELLIGENCE.trackedentity')),
            ],
            options={
                'verbose_name': 'Entity Competitor',
                'verbose_name_plural': 'Entity Competitors',
                'db_table': 'entity_competitors',
                'ordering': ['-priority', 'competitor__name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('mention_spike', 'Mention Spike'), ('negative_spike', 'Negative Sentiment Spike'), ('positive_spike', 'Positive Sentiment Spike'), ('competitor_activity', 'Competitor Activity'), ('keyword_trend', 'Trending Keyword'), ('influencer_mention', 'Influencer Mention'), ('custom', 'Custom Alert')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('trigger_value', models.FloatField(blank=True, help_text='The value that triggered the alert', null=True)),
                ('threshold_value', models.FloatField(blank=True, help_text='The threshold that was exceeded', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_mentions', models.ManyToManyField(blank=True, related_name='alerts', to='SOCIAL_INTELLIGENCE.mention')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='SOCIAL_INTELLIGENCE.trackedentity')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['platform', 'external_post_id'], name='mention_unification_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['published_at', 'is_processed'], name='mentions_publish_1f473a_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['author_username', 'platform'], name='mentions_author__3d5691_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['detected_at', 'is_processed'], name='mentions_detecte_77dc4d_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['creator', 'published_at'], name='mentions_creator_ea2194_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['language', 'published_at'], name='mentions_languag_1b8001_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mention',
            unique_together={('platform', 'external_post_id')},
        ),
        migrations.AddIndex(
            model_name='mentiontopic',
            index=models.Index(fields=['mention', 'topic_name'], name='mention_top_mention_244f72_idx'),
        ),
        migrations.AddIndex(
            model_name='mentiontopic',
            index=models.Index(fields=['topic_name', 'detected_at'], name='mention_top_topic_n_8ebe27_idx'),
        ),
        migrations.AddIndex(
            model_name='mentiontopic',
            index=models.Index(fields=['topic_category', 'detected_at'], name='mention_top_topic_c_6e3ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedentity',
            index=models.Index(fields=['entity_type', 'status'], name='tracked_ent_entity__821bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedentity',
            index=models.Index(fields=['created_at', 'status'], name='tracked_ent_created_7c78d4_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedentity',
            index=models.Index(fields=['brand', 'status'], name='tracked_ent_brand_i_6917f3_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedentity',
            index=models.Index(fields=['creator', 'status'], name='tracked_ent_creator_6047c2_idx'),
        ),
        migrations.AddIndex(
            model_name='mentionsentiment',
            index=models.Index(fields=['mention', 'entity'], name='mention_sen_mention_6d1eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='mentionsentiment',
            index=models.Index(fields=['entity', 'sentiment'], name='mention_sen_entity__d5b765_idx'),
        ),
        migrations.AddIndex(
            model_name='mentionsentiment',
            index=models.Index(fields=['entity', 'analyzed_at'], name='mention_sen_entity__0192bd_idx'),
        ),
        migrations.AddIndex(
            model_name='mentionsentiment',
            index=models.Index(fields=['sentiment', 'analyzed_at'], name='mention_sen_sentime_605185_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentionsentiment',
            unique_together={('mention', 'entity')},
        ),
        migrations.AddIndex(
            model_name='mentionentity',
            index=models.Index(fields=['mention', 'entity'], name='mention_ent_mention_b1beef_idx'),
        ),
        migrations.AddIndex(
            model_name='mentionentity',
            index=models.Index(fields=['entity', 'created_at'], name='mention_ent_entity__30fe17_idx'),
        ),
        migrations.AddIndex(
            model_name='mentionentity',
            index=models.Index(fields=['keyword_matched', 'entity'], name='mention_ent_keyword_7ab911_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mentionentity',
            unique_together={('mention', 'entity')},
        ),
        migrations.AddIndex(
            model_name='extractedkeyword',
            index=models.Index(fields=['keyword', 'entity'], name='extracted_k_keyword_468c70_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedkeyword',
            index=models.Index(fields=['entity', 'trending_score'], name='extracted_k_entity__a04476_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedkeyword',
            index=models.Index(fields=['platform', 'trending_score'], name='extracted_k_platfor_dc3afa_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedkeyword',
            index=models.Index(fields=['first_seen', 'trending_score'], name='extracted_k_first_s_1a07ab_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedkeyword',
            index=models.Index(fields=['last_seen', 'mention_count'], name='extracted_k_last_se_157c62_idx'),
        ),
        migrations.AddIndex(
            model_name='entitykeyword',
            index=models.Index(fields=['entity', 'is_active'], name='entity_keyw_entity__ec9c01_idx'),
        ),
        migrations.AddIndex(
            model_name='entitykeyword',
            index=models.Index(fields=['keyword_type', 'is_active'], name='entity_keyw_keyword_09ed3b_idx'),
        ),
        migrations.AddIndex(
            model_name='entitykeyword',
            index=models.Index(fields=['keyword', 'keyword_type'], name='entity_keyw_keyword_357392_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitykeyword',
            unique_together={('entity', 'keyword', 'keyword_type')},
        ),
        migrations.AddIndex(
            model_name='entitydailystat',
            index=models.Index(fields=['entity', 'date'], name='entity_dail_entity__1a42d1_idx'),
        ),
        migrations.AddIndex(
            model_name='entitydailystat',
            index=models.Index(fields=['date', 'entity'], name='entity_dail_date_14ee76_idx'),
        ),
        migrations.AddIndex(
            model_name='entitydailystat',
            index=models.Index(fields=['entity', 'platform', 'date'], name='entity_dail_entity__649642_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitydailystat',
            unique_together={('entity', 'date', 'platform')},
        ),
        migrations.AddIndex(
            model_name='entitycompetitor',
            index=models.Index(fields=['entity', 'competitor'], name='entity_comp_entity__9b3645_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitycompetitor',
            unique_together={('entity', 'competitor')},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['entity', 'status'], name='alerts_entity__c358cd_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'status'], name='alerts_alert_t_69ec1b_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'status'], name='alerts_severit_ae6d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['triggered_at', 'status'], name='alerts_trigger_63f63c_idx'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entitycompetitor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entitydailystat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entitykeyword',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='extractedkeyword',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mentionentity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mentionsentiment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mentiontopic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trackedentity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
