# Generated by Django 6.0.1 on 2026-01-26 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ANALYTICS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('impression', 'Impression'), ('click', 'Click'), ('like', 'Like'), ('share', 'Share'), ('comment', 'Comment'), ('signup', 'Sign Up'), ('login', 'Login'), ('purchase', 'Purchase'), ('add_to_cart', 'Add to Cart'), ('refund', 'Refund'), ('download', 'Download'), ('search', 'Search'), ('custom', 'Custom')], db_index=True, help_text='Type of analytics event (static choices for MVP)', max_length=50)),
                ('bucket', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], db_index=True, help_text='Aggregation time bucket (day/week/month)', max_length=10)),
                ('bucket_date', models.DateField(db_index=True, help_text='Start date of the aggregation window.\n        Rules:\n        - DAY: exact day (e.g., 2025-01-26)\n        - WEEK: Monday of that week (e.g., 2025-01-20)\n        - MONTH: first day of the month (e.g., 2025-01-01)\n        ')),
                ('event_count', models.PositiveBigIntegerField(default=0, help_text='Total number of events in this bucket')),
                ('metrics_sum', models.JSONField(blank=True, default=dict, help_text='\n        Aggregated numeric metrics.\n        Example:\n        {\n          "impressions": 12000,\n          "views": 4500,\n          "clicks": 890,\n          "revenue": 320.50\n        }\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Brand dimension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_aggregates', to='ANALYTICS.brand')),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign dimension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_aggregates', to='ANALYTICS.campaign')),
                ('content', models.ForeignKey(blank=True, help_text='Content dimension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_aggregates', to='ANALYTICS.content')),
                ('creator', models.ForeignKey(blank=True, help_text='Creator dimension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_aggregates', to='ANALYTICS.creator')),
                ('link', models.ForeignKey(blank=True, help_text='Tracking link dimension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_aggregates', to='ANALYTICS.trackinglink')),
                ('platform', models.ForeignKey(blank=True, help_text='Platform dimension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_aggregates', to='ANALYTICS.platform')),
            ],
            options={
                'verbose_name': 'Analytics Aggregate',
                'verbose_name_plural': 'Analytics Aggregates',
                'db_table': 'analytics_aggregates',
                'ordering': ['-bucket_date', 'event_type'],
                'indexes': [models.Index(fields=['bucket', 'bucket_date'], name='idx_agg_bucket_date'), models.Index(fields=['event_type', 'bucket', 'bucket_date'], name='idx_agg_event_bucket'), models.Index(fields=['campaign', 'bucket_date'], name='idx_agg_campaign_date'), models.Index(fields=['creator', 'bucket_date'], name='idx_agg_creator_date'), models.Index(fields=['brand', 'bucket_date'], name='idx_agg_brand_date')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'platform', 'brand', 'campaign', 'creator', 'content', 'bucket', 'bucket_date'), name='uniq_analytics_aggregate_bucket')],
            },
        ),
    ]
