# Generated by Django 6.0.1 on 2026-01-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANALYTICS', '0001_initial'),
        ('ANALYTICS_AGGREGATES', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analyticsaggregate',
            name='uniq_analytics_aggregate_bucket',
        ),
        migrations.AddIndex(
            model_name='analyticsaggregate',
            index=models.Index(fields=['link', 'bucket_date'], name='idx_agg_link_date'),
        ),
        migrations.AddConstraint(
            model_name='analyticsaggregate',
            constraint=models.UniqueConstraint(fields=('event_type', 'platform', 'brand', 'campaign', 'creator', 'content', 'bucket', 'bucket_date', 'link'), name='uniq_analytics_aggregate_bucket'),
        ),
    ]
