# Generated by Django 5.2.11 on 2026-03-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0005_country_emailverification_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['code'], name='AUTH_countr_code_bd1e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_active'], name='AUTH_countr_is_acti_ecb704_idx'),
        ),
    ]
