# Generated by Django 5.2.11 on 2026-02-24 21:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ANALYTICS', '0004_campaigndailystat_contentdailystat_creatordailystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEfficiencyScore',
            fields=[
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='efficiency_score', serialize=False, to='ANALYTICS.campaign')),
                ('total_impressions', models.BigIntegerField(default=0)),
                ('total_engagements', models.BigIntegerField(default=0)),
                ('total_clicks', models.BigIntegerField(default=0)),
                ('total_conversions', models.BigIntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('roi', models.FloatField(blank=True, null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cpe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('engagement_rate', models.FloatField(blank=True, null=True)),
                ('conversion_rate', models.FloatField(blank=True, null=True)),
                ('sentiment_shift', models.FloatField(blank=True, null=True)),
                ('positive_shift_percentage', models.FloatField(blank=True, null=True)),
                ('negative_shift_percentage', models.FloatField(blank=True, null=True)),
                ('efficiency_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('roi_normalized', models.FloatField(blank=True, null=True)),
                ('cpc_normalized', models.FloatField(blank=True, null=True)),
                ('cpe_normalized', models.FloatField(blank=True, null=True)),
                ('conversion_rate_normalized', models.FloatField(blank=True, null=True)),
                ('sentiment_normalized', models.FloatField(blank=True, null=True)),
                ('engagement_rate_normalized', models.FloatField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign Efficiency Score',
                'verbose_name_plural': 'Campaign Efficiency Scores',
                'db_table': 'campaign_efficiency_scores',
            },
        ),
        migrations.CreateModel(
            name='CampaignCreator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreed_fee', models.DecimalField(decimal_places=2, help_text='Agreed payment for this creator', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_posts', models.IntegerField(help_text='Number of posts expected', validators=[django.core.validators.MinValueValidator(1)])),
                ('actual_posts', models.IntegerField(default=0, help_text='Number of posts delivered', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='invited', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_creators', to='ANALYTICS.campaign')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_creator_links', to='ANALYTICS.creatorcontract')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to='ANALYTICS.creator')),
            ],
            options={
                'verbose_name': 'Campaign Creator',
                'verbose_name_plural': 'Campaign Creators',
                'db_table': 'campaign_creators',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'Twitter (X)'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], db_index=True, help_text='Social media platform', max_length=20)),
                ('external_post_id', models.CharField(db_index=True, help_text='Platform-specific ID (Instagram Media ID, TikTok Video ID, etc.)', max_length=255)),
                ('post_url', models.URLField(help_text='Direct URL to the post', max_length=500)),
                ('content_type', models.CharField(choices=[('reel', 'Reel/Short'), ('story', 'Story'), ('static', 'Static Post'), ('video', 'Video'), ('carousel', 'Carousel'), ('thread', 'Thread'), ('live', 'Live Stream')], help_text='Format of content', max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('posted_at', models.DateTimeField(db_index=True, help_text='When published on platform')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_posts', to='ANALYTICS.campaign')),
                ('campaign_creator', models.ForeignKey(help_text='Links to CampaignCreator junction', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_posts', to='CAMPAIGN_INTELLIGENCE.campaigncreator')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_posts', to='ANALYTICS.creator')),
            ],
            options={
                'verbose_name': 'Campaign Post',
                'verbose_name_plural': 'Campaign Posts',
                'db_table': 'campaign_posts',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorPerformanceAggregate',
            fields=[
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='performance_aggregate', serialize=False, to='ANALYTICS.creator')),
                ('total_campaigns', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_impressions', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_engagements', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_clicks', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_conversions', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_engagement_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_cpc', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_cpe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_conversion_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_hook_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_watch_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_sentiment_shift', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('lifetime_efficiency_score', models.FloatField(blank=True, help_text='Weighted lifetime score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hybrid_weight_score', models.FloatField(blank=True, help_text='Total hybrid weight (for debugging)', null=True)),
                ('global_rank', models.IntegerField(blank=True, null=True)),
                ('global_percentile', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Creator Performance Aggregate',
                'verbose_name_plural': 'Creator Performance Aggregates',
                'db_table': 'creator_performance_aggregate',
                'ordering': ['-lifetime_efficiency_score'],
                'indexes': [models.Index(fields=['-lifetime_efficiency_score'], name='creator_per_lifetim_ef7f5e_idx'), models.Index(fields=['global_rank'], name='creator_per_global__1d7f55_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreatorScoreHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_score', models.FloatField(help_text='Creator efficiency score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hybrid_weight', models.FloatField(help_text='0.4*spend + 0.3*impressions + 0.3*engagements')),
                ('spend_weight', models.FloatField(blank=True, null=True)),
                ('impression_weight', models.FloatField(blank=True, null=True)),
                ('engagement_weight', models.FloatField(blank=True, null=True)),
                ('campaign_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('campaign_impressions', models.BigIntegerField(default=0)),
                ('campaign_engagements', models.BigIntegerField(default=0)),
                ('campaign_clicks', models.BigIntegerField(default=0)),
                ('campaign_conversions', models.BigIntegerField(default=0)),
                ('tier', models.CharField(blank=True, help_text='Low, Moderate, High, Elite', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_scores', to='ANALYTICS.campaign')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='ANALYTICS.creator')),
            ],
            options={
                'verbose_name': 'Creator Score History',
                'verbose_name_plural': 'Creator Score Histories',
                'db_table': 'creator_score_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaigncreator',
            index=models.Index(fields=['campaign', 'creator'], name='campaign_cr_campaig_b56edf_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncreator',
            index=models.Index(fields=['campaign', 'status'], name='campaign_cr_campaig_9e18c7_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncreator',
            index=models.Index(fields=['creator', 'status'], name='campaign_cr_creator_622176_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigncreator',
            unique_together={('campaign', 'creator')},
        ),
        migrations.AddIndex(
            model_name='campaignpost',
            index=models.Index(fields=['platform', 'external_post_id'], name='post_unique_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignpost',
            index=models.Index(fields=['campaign', 'status'], name='campaign_po_campaig_045440_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignpost',
            index=models.Index(fields=['creator', 'campaign'], name='campaign_po_creator_878cea_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignpost',
            index=models.Index(fields=['campaign_creator', 'status'], name='campaign_po_campaig_ae139e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignpost',
            index=models.Index(fields=['posted_at', 'status'], name='campaign_po_posted__c88ff8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignpost',
            unique_together={('platform', 'external_post_id')},
        ),
        migrations.AddIndex(
            model_name='creatorscorehistory',
            index=models.Index(fields=['creator', '-created_at'], name='creator_sco_creator_75f7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorscorehistory',
            index=models.Index(fields=['campaign', '-campaign_score'], name='creator_sco_campaig_17a0a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='creatorscorehistory',
            unique_together={('creator', 'campaign')},
        ),
    ]
