# Generated by Django 5.2.11 on 2026-02-26 11:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAMPAIGN_INTELLIGENCE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorperformanceaggregate',
            name='hybrid_weight_score',
            field=models.FloatField(blank=True, help_text='Sum of all hybrid weights: Σ(0.4×spend + 0.3×impressions + 0.3×engagements) across all campaigns. Used as denominator for weighted averages.', null=True),
        ),
        migrations.AlterField(
            model_name='creatorscorehistory',
            name='campaign_score',
            field=models.FloatField(help_text='Creator efficiency score for this campaign (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='creatorscorehistory',
            name='hybrid_weight',
            field=models.FloatField(help_text='0.4×spend + 0.3×impressions + 0.3×engagements for this campaign'),
        ),
        migrations.CreateModel(
            name='CampaignScopedCreatorEfficiency',
            fields=[
                ('campaign_creator', models.OneToOneField(help_text='One efficiency record per campaign-creator pairing', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scoped_efficiency', serialize=False, to='CAMPAIGN_INTELLIGENCE.campaigncreator')),
                ('engagement_rate', models.FloatField(blank=True, help_text='Engagements / Impressions × 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cpc', models.DecimalField(blank=True, decimal_places=4, help_text='Cost Per Click', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cpe', models.DecimalField(blank=True, decimal_places=4, help_text='Cost Per Engagement', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('hook_rate', models.FloatField(blank=True, help_text='3-second view rate (video only)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('watch_rate', models.FloatField(blank=True, help_text='Average watch percentage (video only)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('conversion_rate', models.FloatField(blank=True, help_text='Conversions / Clicks × 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sentiment_shift', models.FloatField(blank=True, help_text='Net sentiment change (post - pre campaign)', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('engagement_rate_normalized', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cpc_normalized', models.FloatField(blank=True, help_text='Inverted: lower CPC = higher score', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cpe_normalized', models.FloatField(blank=True, help_text='Inverted: lower CPE = higher score', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hook_rate_normalized', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('watch_rate_normalized', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('conversion_rate_normalized', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sentiment_shift_normalized', models.FloatField(blank=True, help_text='Shifted to 0-100 scale: (value + 100) / 2', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('efficiency_score', models.FloatField(blank=True, help_text='Weighted score (0-100) from normalized metrics', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_engagement_rate', models.FloatField(default=0.2)),
                ('weight_cpc', models.FloatField(default=0.15)),
                ('weight_cpe', models.FloatField(default=0.15)),
                ('weight_hook_rate', models.FloatField(default=0.1)),
                ('weight_watch_rate', models.FloatField(default=0.1)),
                ('weight_conversion_rate', models.FloatField(default=0.2)),
                ('weight_sentiment_shift', models.FloatField(default=0.1)),
                ('percentile_rank', models.FloatField(blank=True, help_text='Percentile rank within campaign (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tier', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('elite', 'Elite')], help_text='Performance tier within campaign', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign-Scoped Creator Efficiency',
                'verbose_name_plural': 'Campaign-Scoped Creator Efficiencies',
                'db_table': 'campaign_scoped_creator_efficiency',
                'ordering': ['-efficiency_score'],
                'indexes': [models.Index(fields=['-efficiency_score'], name='campaign_sc_efficie_665a4d_idx'), models.Index(fields=['percentile_rank'], name='campaign_sc_percent_53111d_idx')],
            },
        ),
    ]
