# Generated by Django 5.2.11 on 2026-02-27 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAMPAIGN_INTELLIGENCE', '0002_alter_creatorperformanceaggregate_hybrid_weight_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorscorehistory',
            name='engagement_weight',
        ),
        migrations.RemoveField(
            model_name='creatorscorehistory',
            name='hybrid_weight',
        ),
        migrations.RemoveField(
            model_name='creatorscorehistory',
            name='impression_weight',
        ),
        migrations.RemoveField(
            model_name='creatorscorehistory',
            name='spend_weight',
        ),
        migrations.AddField(
            model_name='campaignscopedcreatorefficiency',
            name='total_3sec_views',
            field=models.BigIntegerField(default=0, help_text='Total 3-second views (hook metric)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='campaignscopedcreatorefficiency',
            name='total_clicks',
            field=models.BigIntegerField(default=0, help_text='Total link clicks', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='campaignscopedcreatorefficiency',
            name='total_conversions',
            field=models.BigIntegerField(default=0, help_text='Total conversions (sales, signups, etc.)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='campaignscopedcreatorefficiency',
            name='total_engagements',
            field=models.BigIntegerField(default=0, help_text='Total engagements (likes + comments + shares + saves)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='campaignscopedcreatorefficiency',
            name='total_impressions',
            field=models.BigIntegerField(default=0, help_text='Total impressions for this creator in this campaign', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='campaignscopedcreatorefficiency',
            name='total_spend',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Creator fee paid for this campaign', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='campaignscopedcreatorefficiency',
            name='total_video_views',
            field=models.BigIntegerField(default=0, help_text='Total video views (for video content only)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='campaignscopedcreatorefficiency',
            name='total_watch_time_seconds',
            field=models.BigIntegerField(default=0, help_text='Total watch time in seconds', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='creatorscorehistory',
            name='engagement_weight_raw',
            field=models.FloatField(blank=True, default=None, help_text='0.3 × engagements', null=True),
        ),
        migrations.AddField(
            model_name='creatorscorehistory',
            name='hybrid_weight_proportional',
            field=models.FloatField(blank=True, default=None, help_text='Proportional weight: raw_weight / Σ(all_raw_weights). Used in weighted averages.', null=True),
        ),
        migrations.AddField(
            model_name='creatorscorehistory',
            name='hybrid_weight_raw',
            field=models.FloatField(default=0.0, help_text='Raw: 0.4×spend + 0.3×impressions + 0.3×engagements'),
        ),
        migrations.AddField(
            model_name='creatorscorehistory',
            name='impression_weight_raw',
            field=models.FloatField(blank=True, default=None, help_text='0.3 × impressions', null=True),
        ),
        migrations.AddField(
            model_name='creatorscorehistory',
            name='spend_weight_raw',
            field=models.FloatField(blank=True, default=None, help_text='0.4 × spend', null=True),
        ),
        migrations.AlterField(
            model_name='campaignefficiencyscore',
            name='conversion_rate',
            field=models.FloatField(blank=True, help_text='Conv Rate (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignefficiencyscore',
            name='efficiency_score',
            field=models.FloatField(blank=True, help_text='Campaign efficiency (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignefficiencyscore',
            name='engagement_rate',
            field=models.FloatField(blank=True, help_text='ER (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignefficiencyscore',
            name='negative_shift_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignefficiencyscore',
            name='positive_shift_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignefficiencyscore',
            name='roi',
            field=models.FloatField(blank=True, help_text='ROI as percentage', null=True),
        ),
        migrations.AlterField(
            model_name='campaignefficiencyscore',
            name='sentiment_shift',
            field=models.FloatField(blank=True, help_text='Sentiment shift (-100 to +100)', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='conversion_rate',
            field=models.FloatField(blank=True, help_text='(Conversions / Clicks) × 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='conversion_rate_normalized',
            field=models.FloatField(blank=True, help_text='Min-Max normalized conv rate (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='cpc',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cost Per Click (Spend / Clicks)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='cpc_normalized',
            field=models.FloatField(blank=True, help_text='INVERTED: lower CPC = higher score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='cpe',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cost Per Engagement (Spend / Engagements)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='cpe_normalized',
            field=models.FloatField(blank=True, help_text='INVERTED: lower CPE = higher score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='engagement_rate',
            field=models.FloatField(blank=True, help_text='(Engagements / Impressions) × 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='engagement_rate_normalized',
            field=models.FloatField(blank=True, help_text='Min-Max normalized ER (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='hook_rate',
            field=models.FloatField(blank=True, help_text='(3-sec views / Impressions) × 100 (video only)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='hook_rate_normalized',
            field=models.FloatField(blank=True, help_text='Min-Max normalized hook rate (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='sentiment_shift',
            field=models.FloatField(blank=True, help_text='Net sentiment change (post - pre campaign), range: -100 to +100', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='tier',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('elite', 'Elite')], editable=False, help_text='Performance tier (enforced by scoring_service.py based on percentile_rank)', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='watch_rate',
            field=models.FloatField(blank=True, help_text='(Total watch time / Total video duration) × 100 (video only)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='watch_rate_normalized',
            field=models.FloatField(blank=True, help_text='Min-Max normalized watch rate (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='weight_conversion_rate',
            field=models.FloatField(default=0.2, help_text='Weight for conv rate in final score'),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='weight_cpc',
            field=models.FloatField(default=0.15, help_text='Weight for CPC in final score'),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='weight_cpe',
            field=models.FloatField(default=0.15, help_text='Weight for CPE in final score'),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='weight_engagement_rate',
            field=models.FloatField(default=0.2, help_text='Weight for ER in final score'),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='weight_hook_rate',
            field=models.FloatField(default=0.1, help_text='Weight for hook rate in final score'),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='weight_sentiment_shift',
            field=models.FloatField(default=0.1, help_text='Weight for sentiment in final score'),
        ),
        migrations.AlterField(
            model_name='campaignscopedcreatorefficiency',
            name='weight_watch_rate',
            field=models.FloatField(default=0.1, help_text='Weight for watch rate in final score'),
        ),
        migrations.AlterField(
            model_name='creatorperformanceaggregate',
            name='avg_conversion_rate',
            field=models.FloatField(blank=True, help_text='Weighted avg Conv Rate (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='creatorperformanceaggregate',
            name='avg_cpc',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Weighted avg Cost Per Click', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creatorperformanceaggregate',
            name='avg_cpe',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Weighted avg Cost Per Engagement', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creatorperformanceaggregate',
            name='avg_engagement_rate',
            field=models.FloatField(blank=True, help_text='Weighted avg ER (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='creatorperformanceaggregate',
            name='avg_hook_rate',
            field=models.FloatField(blank=True, help_text='Weighted avg Hook Rate (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='creatorperformanceaggregate',
            name='avg_sentiment_shift',
            field=models.FloatField(blank=True, help_text='Weighted avg Sentiment Shift (-100 to +100)', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='creatorperformanceaggregate',
            name='avg_watch_rate',
            field=models.FloatField(blank=True, help_text='Weighted avg Watch Rate (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='creatorperformanceaggregate',
            name='global_percentile',
            field=models.FloatField(blank=True, help_text='Global percentile (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='creatorperformanceaggregate',
            name='hybrid_weight_score',
            field=models.FloatField(blank=True, help_text='Sum of raw hybrid weights: Σ(0.4×spend + 0.3×impressions + 0.3×engagements). For reference only - actual weighting uses PROPORTIONAL normalized weights.', null=True),
        ),
        migrations.AlterField(
            model_name='creatorscorehistory',
            name='tier',
            field=models.CharField(blank=True, help_text='Low, Moderate, High, Elite (from CampaignScopedCreatorEfficiency)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='campaignscopedcreatorefficiency',
            index=models.Index(fields=['tier'], name='campaign_sc_tier_4a4610_idx'),
        ),
    ]
